[workspace]
authors = ["skarakuzu <karakuzu.seher@gmail.com>"]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks.lab]
cmd = "jupyter lab"
[tasks.start]
depends-on = ["lab"]

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"
