[workspace]
authors = ["skarakuzu <karakuzu.seher@gmail.com>"]
channels = ["conda-forge"]
name = "create-envs"
platforms = ["osx-64", "linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.1,<3"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"

[feature.gpu.target.win-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]

